spring.application.name=routina
spring.datasource.url=${DATASOURCE}
spring.datasource.username=${DATAUSER}
spring.datasource.password=${DATAPASS}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view = false
jwt.secret=${JWT_SECRET}
jwt.expiration = 3600000
